### ISSUE TITLE
Compling issue

### ISSUE THREAD

**Issue by thelostman436** [Luminate-D/protanki-server#1]
I tried compling the server with maven and i got this error
![image](https://github.com/Luminate-D/protanki-server/assets/128747372/a7976c76-1d8e-4530-a20c-3e907f2a5bfc)

**Comment by 1DreamStan** [comment]
sounds like skill issue

**Comment by Wer0000** [comment]
[pom.txt](https://github.com/Luminate-D/protanki-server/files/12252021/pom.txt)

**Comment by Wer0000** [comment]
[pom.txt](https://github.com/Luminate-D/protanki-server/files/12300702/pom.txt)

**Comment by Wer0000** [comment]
[pom.txt](https://github.com/Luminate-D/protanki-server/files/12315795/pom.txt)

**Comment by Wer0000** [comment]
• upd 18.08.2023

[pom.txt](https://github.com/Luminate-D/protanki-server/files/12378293/pom.txt)
