### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by WolfAURman** [Luminate-D/protanki-server#2]
After build I get this error, how can I fix it?
![изображение](https://github.com/Luminate-D/protanki-server/assets/93985232/f6093734-e745-4a6a-bded-b3166c81779a)
Build commands:
```
mvn clean install
mvn package
```
What did I do wrong? I have already collected similar projects before, and these commands worked

**Comment by TheEntropyShard** [comment]
If you check pom.xml, you see, there is no way to build so-called "fat jar" (jar-with-dependencies). You need to add Maven assembly plugin to build executable jars and give it fully-qualified-name of main class. You can find more info on this on the Internet

**Comment by TheEntropyShard** [comment]
[Here](https://github.com/Luminate-D/protanki-server/issues/1) you can find the pom.xml that you need. Just download it into your project folder, delete pom.xml, rename pom.txt to pom.xml and try to build and run again
