### ISSUE TITLE
AnnotationHelper ERROR

### ISSUE THREAD

**Issue by Wer0000** [Luminate-D/protanki-server#3]
![Снимок экрана (133)](https://github.com/Luminate-D/protanki-server/assets/60045423/9c5185d5-3212-40a0-bcbb-a97f6ce79510)

**Comment by Wer0000** [comment]
![Снимок экрана (133)](https://github.com/Luminate-D/protanki-server/assets/60045423/a53325d0-890b-4a3f-a120-8adbcc15bded)

**Comment by Wer0000** [comment]
[AnnotationHelper.txt](https://github.com/Luminate-D/protanki-server/files/12378463/AnnotationHelper.txt)
•UPD

fix

**Comment by WolfAURman** [comment]
> [AnnotationHelper.txt](https://github.com/Luminate-D/protanki-server/files/12378463/AnnotationHelper.txt) •UPD
> 
> fix

I'm facing the same problem, how do I make this fix?

**Comment by TheEntropyShard** [comment]
In my case it works, without any problems

**Comment by Luminate-D** [comment]
This error shouldnt appear, make sure you build project correcly, with bundling resources into it.

**Comment by Wer0000** [comment]
I'm fine with the old version, but your new one has something wrong.

**Comment by Wer0000** [comment]
NullPointerException error, which means that a null object is treated as a normal object.
